version: '2'
services:
  host1:
    image: ovn_lab:v1 
    container_name: host1
    hostname: host1
    command: bash -c 'while true;do sleep 10;done' 
    privileged: true
    environment:
      TERM: linux
      MY_IP: 10.10.0.10
    ports:
      - "16640:6640"
    networks:
      ovnnet:
         ipv4_address: 10.10.0.10 
    volumes:
      - .:/root/ovn_lab
  host2:
    image: ovn_lab:v1
    container_name: host2
    hostname: host2
    command: bash -c 'while true;do sleep 10;done'
    privileged: true
    environment:
      TERM: linux
      OVN_SERVER: 10.10.0.10
      MY_IP: 10.10.0.20
    ports:
      - "26640:6640"
    networks:
      ovnnet:
        ipv4_address: 10.10.0.20
    volumes:
      - .:/root/ovn_lab
     

networks:
  ovnnet:
    external: true
    
